### ISSUE TITLE
The Nuklear demo has compilation errors

### ISSUE THREAD

**Issue by codedcosmos** [LWJGL/lwjgl3#400]
The nuklear demo, [GLFWDemo](https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/nuklear/GLFWDemo.java) won't run because of the two points in the code. Specificly lines 237 and 477 (the lamba expression parts)

This might be a problem on my part, or a problem with the code itself im not entirely sure.

For what its worth here is the error

`Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The method texture(NkHandle) in the type NkUserFont is not applicable for the arguments ((<no type> it) -> {})
	The target type of this expression must be a functional interface`

Replacing the code at line 237 with `.texture();` and removing the entire clip part, causes the code to run, but font textures are missing.

**Comment by kenzierocks** [comment]
How are you running the demos? The feature used there is only present in the latest snapshots, so if you're attempting to run it on 3.1.6 it won't work.

**Comment by codedcosmos** [comment]
I was copying the classes required (Calculator, Demo, GLFWDemo and IOUtil).

It works on 3.17 Nightly. Is there a way to run it on 3.16?

**Comment by httpdigest** [comment]
Yes, go back in Git history and use this revision: https://github.com/LWJGL/lwjgl3/tree/00e1f52cf95c16b0cea34c83372145532b4745ba/modules/samples/src/test/java/org/lwjgl/demo/nuklear
